/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class frmPeminjaman extends javax.swing.JFrame {

    /**
     * Creates new form frmPeminjaman
     */
    public frmPeminjaman() {
        initComponents();
        tampilkanData();
        tampilkanCmbAnggota();
        tampilkanCmbBuku();
        tampilkanCmbPegawai();
        kosongkanForm();
    }
    
    public void kosongkanForm() {
    txtIdPeminjaman.setText("0");
    cmbAnggota.setSelectedIndex(0);
    cmbBuku.setSelectedIndex(0);
    cmbPegawai.setSelectedIndex(0);
    txtTanggalPinjam.setText(LocalDate.now().toString());
    txtTanggalKembali.setText(LocalDate.now().toString());
    txtTanggalKembali.setEnabled(false); // Menonaktifkan kolom Tanggal Kembali saat form dibuka

}

public void tampilkanData() {
    String[] kolom = {"ID Peminjaman", "Anggota", "Buku", "Pegawai", "Tanggal Pinjam", "Tanggal Kembali"};
    ArrayList<Peminjaman> list = new Peminjaman().getAll();
    Object rowData[] = new Object[6];

    tblPeminjaman.setModel(new DefaultTableModel(new Object[][]{}, kolom));

    for (Peminjaman peminjaman : list) {
        rowData[0] = peminjaman.getIdpeminjaman();
        rowData[1] = peminjaman.getAnggota().getNama();
        rowData[2] = peminjaman.getBuku().getJudul();
        rowData[3] = peminjaman.getPegawai().getNama();
        rowData[4] = peminjaman.getTanggalPinjam();
        rowData[5] = peminjaman.getTanggalKembali();
        

        ((DefaultTableModel) tblPeminjaman.getModel()).addRow(rowData);
    }
}

private LocalDate parseDate(String date) {
    try {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        return LocalDate.parse(date, formatter);
    } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this, "Format tanggal salah. Gunakan format YYYY-MM-DD.", "Error", JOptionPane.ERROR_MESSAGE);
        return null;
    }
}


public void tampilkanCmbAnggota() {
    cmbAnggota.setModel(new DefaultComboBoxModel(new Anggota().getAll().toArray()));
}

public void tampilkanCmbBuku() {
    cmbBuku.setModel(new DefaultComboBoxModel(new Buku().getAll().toArray()));
}

public void tampilkanCmbPegawai() {
    cmbPegawai.setModel(new DefaultComboBoxModel(new Pegawai().getAll().toArray()));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdPeminjaman = new javax.swing.JTextField();
        txtTanggalPinjam = new javax.swing.JTextField();
        txtTanggalKembali = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPeminjaman = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbBuku = new javax.swing.JComboBox<>();
        cmbAnggota = new javax.swing.JComboBox<>();
        cmbPegawai = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("ID Anggota");

        jLabel3.setText("ID Buku");

        jLabel4.setText("ID Pegawai");

        jLabel5.setText("Tanggal Pinjam");

        jLabel6.setText("Tanggal Kembali");

        txtIdPeminjaman.setEnabled(false);
        txtIdPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPeminjamanActionPerformed(evt);
            }
        });

        txtTanggalPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalPinjamActionPerformed(evt);
            }
        });

        txtTanggalKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalKembaliActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tblPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPeminjaman);

        jLabel10.setText("Format YYYY:MM:DD");

        jLabel11.setText("Format YYYY:MM:DD");

        cmbBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbAnggota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnTambah)
                                .addGap(28, 28, 28)
                                .addComponent(btnUpdate))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cmbBuku, 0, 139, Short.MAX_VALUE)
                                            .addComponent(cmbAnggota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbPegawai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTanggalPinjam))
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)))
                                    .addComponent(txtIdPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(txtTanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnSimpan)
                    .addComponent(btnTambah))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPeminjamanActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        // Ambil tanggal pinjam
        LocalDate tanggalPinjam = parseDate(txtTanggalPinjam.getText());
        LocalDate tanggalKembali = parseDate(txtTanggalKembali.getText());
        
        // Validasi tanggal
        if (tanggalKembali.isBefore(tanggalPinjam)) {
            JOptionPane.showMessageDialog(this, "Tanggal kembali tidak boleh lebih awal dari tanggal pinjam.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Proses penyimpanan data
        Peminjaman peminjaman = new Peminjaman();
        peminjaman.setIdpeminjaman(Integer.parseInt(txtIdPeminjaman.getText()));
        peminjaman.setAnggota((Anggota) cmbAnggota.getSelectedItem());
        peminjaman.setBuku((Buku) cmbBuku.getSelectedItem());
        peminjaman.setPegawai((Pegawai) cmbPegawai.getSelectedItem());
        peminjaman.setTanggalPinjam(tanggalPinjam);
        peminjaman.setTanggalKembali(tanggalKembali); 

        peminjaman.save();
        
        txtIdPeminjaman.setText(Integer.toString(peminjaman.getIdpeminjaman()));

        tampilkanData();
        kosongkanForm();
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan.");

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int row = tblPeminjaman.getSelectedRow();

    if (row != -1) {
        // Ambil data dari form dan hanya perbarui tanggal kembali
        Peminjaman peminjaman = new Peminjaman();
        peminjaman.setIdpeminjaman(Integer.parseInt(txtIdPeminjaman.getText()));
        peminjaman.setTanggalPinjam(parseDate(txtTanggalPinjam.getText())); // Tidak diubah
        peminjaman.setTanggalKembali(LocalDate.parse(txtTanggalKembali.getText())); // Update tanggal kembali sesuai input

        // Perbarui data di database
        peminjaman.update();

        // Nonaktifkan semua input setelah update
        txtIdPeminjaman.setEnabled(false);
        txtTanggalPinjam.setEnabled(false);
        cmbAnggota.setEnabled(false);
        cmbBuku.setEnabled(false);
        cmbPegawai.setEnabled(false);
        txtTanggalKembali.setEnabled(false); // Nonaktifkan setelah update

        // Menandai baris di tabel agar tidak bisa diklik lagi
        DefaultTableModel model = (DefaultTableModel) tblPeminjaman.getModel();
        // Menandai baris yang telah diupdate sebagai tidak dapat dipilih
        model.setValueAt("Updated", row, 0); // Menandai kolom pertama (misalnya ID) sebagai "Updated"

        tampilkanData(); // Memperbarui tampilan tabel
        kosongkanForm(); // Kosongkan form input setelah update
        JOptionPane.showMessageDialog(this, "Tanggal kembali berhasil diperbarui.");
    } else {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin diupdate!");
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtTanggalPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalPinjamActionPerformed

    private void txtTanggalKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalKembaliActionPerformed

    private void tblPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeminjamanMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
    DefaultTableModel model = (DefaultTableModel) tblPeminjaman.getModel();
    int row = tblPeminjaman.getSelectedRow();

    if (row != -1) { // Pastikan ada baris yang dipilih
        try {
            // Ambil ID peminjaman dari tabel
            int idPeminjaman = Integer.parseInt(model.getValueAt(row, 0).toString());

            // Ambil data peminjaman berdasarkan ID
            Peminjaman peminjaman = new Peminjaman().getById(idPeminjaman);

            if (peminjaman != null) {
                // Set data ke form
                txtIdPeminjaman.setText(String.valueOf(peminjaman.getIdpeminjaman()));

                // Pastikan combo box dapat mengenali objek yang cocok
                cmbAnggota.setSelectedItem(peminjaman.getAnggota());
                cmbBuku.setSelectedItem(peminjaman.getBuku());
                cmbPegawai.setSelectedItem(peminjaman.getPegawai());

                // Format tanggal untuk ditampilkan di form
                txtTanggalPinjam.setText(peminjaman.getTanggalPinjam().toString());
                txtTanggalKembali.setText(peminjaman.getTanggalKembali() != null
                        ? peminjaman.getTanggalKembali().toString()
                        : ""); // Kosongkan jika tanggal kembali belum diatur
                 
                // Nonaktifkan semua field kecuali txtTanggalKembali
                txtIdPeminjaman.setEnabled(false);
                txtTanggalPinjam.setEnabled(false);
                cmbAnggota.setEnabled(false);
                cmbBuku.setEnabled(false);
                cmbPegawai.setEnabled(false);
                txtTanggalKembali.setEnabled(true); // Hanya tanggalKembali yang dapat diedit
            } else {
                JOptionPane.showMessageDialog(this, "Data peminjaman tidak ditemukan.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Format ID peminjaman salah.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_tblPeminjamanMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
        txtIdPeminjaman.setEnabled(true);
    txtTanggalPinjam.setEnabled(true);
    cmbAnggota.setEnabled(true);
    cmbBuku.setEnabled(true);
    cmbPegawai.setEnabled(true);
    txtTanggalKembali.setEnabled(false);
    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPeminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbAnggota;
    private javax.swing.JComboBox<String> cmbBuku;
    private javax.swing.JComboBox<String> cmbPegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblPeminjaman;
    private javax.swing.JTextField txtIdPeminjaman;
    private javax.swing.JTextField txtTanggalKembali;
    private javax.swing.JTextField txtTanggalPinjam;
    // End of variables declaration//GEN-END:variables
}
